### ISSUE TITLE
deprecated zmq send/recv calls

### ISSUE THREAD

**Issue by russkel** [GobySoft/goby3#106]
Seems as of ZMQ 4.3.1 some of these calls have become deprecated.
```
[140/228] Building CXX object src/zeromq/CMakeFiles/goby_zeromq.dir/transport/interprocess.cpp.o
../src/zeromq/transport/interprocess.cpp: In member function 'bool goby::zeromq::InterProcessPortalMainThread::recv(goby::zeromq::protobuf::InprocControl*, int)':
../src/zeromq/transport/interprocess.cpp:74:45: warning: 'bool zmq::detail::socket_base::recv(zmq::message_t*, int)' is deprecated: from 4.3.1, use recv taking a reference to message_t and recv_flags [-Wdeprecated-declarations]
     if (control_socket_.recv(&zmq_msg, flags))
                                             ^
In file included from ../src/zeromq/transport/interprocess.h:27,
                 from ../src/zeromq/transport/interprocess.cpp:25:
/usr/include/zmq.hpp:1267:10: note: declared here
     bool recv(message_t *msg_, int flags_ = 0)
          ^~~~
../src/zeromq/transport/interprocess.cpp: In member function 'void goby::zeromq::InterProcessPortalMainThread::publish(const string&, const char*, int)':
../src/zeromq/transport/interprocess.cpp:107:33: warning: 'bool zmq::detail::socket_base::send(zmq::message_t&, int)' is deprecated: from 4.3.1, use send taking message_t and send_flags [-Wdeprecated-declarations]
         publish_socket_.send(msg);
                                 ^
In file included from ../src/zeromq/transport/interprocess.h:27,
                 from ../src/zeromq/transport/interprocess.cpp:25:
/usr/include/zmq.hpp:1191:10: note: declared here
     bool send(message_t &msg_,
          ^~~~
```

**Comment by adityabharadwaj14** [comment]
I keep getting this warning as well. I did not understand your method to get rid of those warnings. Could you please explain this?

**Comment by russkel** [comment]
> I keep getting this warning as well. I did not understand your method to get rid of those warnings. Could you please explain this?

If you update to latest version this is now fixed. Alternatively you can disable zmq support.

**Comment by adityabharadwaj14** [comment]
> > I keep getting this warning as well. I did not understand your method to get rid of those warnings. Could you please explain this?
> 
> If you update to latest version this is now fixed. Alternatively you can disable zmq support.

Could you please elaborate on how to do that? Both the update and disabling XML support. 

I had downloaded the zmqcpp repository and had installed from source. So just inquiring on the next step

**Comment by russkel** [comment]
> Could you please elaborate on how to do that?

Git pull/download the latest version of goby3 codebase.

> disabling XML support.

It's a CMake "option", see https://github.com/GobySoft/goby3/blob/3.0/src/CMakeLists.txt#L238

When calling cmake you can add to the command line `-Dbuild_zeromq=OFF`. CMake will no longer build zeromq components for Goby.

**Comment by adityabharadwaj14** [comment]
> > Could you please elaborate on how to do that?
> 
> Git pull/download the latest version of goby3 codebase.
> 
> > disabling XML support.
> 
> It's a CMake "option", see https://github.com/GobySoft/goby3/blob/3.0/src/CMakeLists.txt#L238
> 
> When calling cmake you can add to the command line `-Dbuild_zeromq=OFF`. CMake will no longer build zeromq components for Goby.

I tried the above mentioned method. However it didnot work. The thing is i installed zmq fro c++ based on the procedure mentioned here https://github.com/zeromq/cppzmq . I would like to know if there's an installation procedure that can avoid these errors. I would prefer to not make any changes to the makefile of the example program.

 warning: ‘bool zmq::detail::socket_base::recv(zmq::message_t*, int)’ is deprecated: from 4.3.1, use recv taking a reference to message_t and recv_flags [-Wdeprecated-declarations]
         socket.recv(&request);
                             ^
In file included from /mnt/hgfs/home/Zeromq/ServerProgram/main.cpp:1:0:
/usr/local/include/zmq.hpp:1874:10: note: declared here
     bool recv(message_t *msg_, int flags_ = 0)
          ^~~~
/mnt/hgfs/home/Zeromq/ServerProgram/main.cpp:29:26: warning: ‘bool zmq::detail::socket_base::send(zmq::message_t&, int)’ is deprecated: from 4.3.1, use send taking message_t and send_flags [-Wdeprecated-declarations]
         socket.send(reply);
                          ^
In file included from /mnt/hgfs/home/Zeromq/ServerProgram/main.cpp:1:0:
/usr/local/include/zmq.hpp:1793:10: note: declared here
     bool send(message_t &msg_,
          ^~~~
