### ISSUE TITLE
Expired Key for Goby Soft Packages

### ISSUE THREAD

**Issue by joelslaby** [GobySoft/goby3#197]
Did the public key expire for the goby soft packages repository?

My trusted.gpg shows:
![image](https://user-images.githubusercontent.com/8798113/114117252-49863700-98b4-11eb-8fde-59b7aa0dffd2.png)

And my sudo apt update:
![image](https://user-images.githubusercontent.com/8798113/114117271-54d96280-98b4-11eb-8975-e20532f0f33c.png)

**Comment by tsaubergine** [comment]
Sorry for this, should be fixed now. Please do:

```
sudo apt-key adv --recv-key --keyserver keyserver.ubuntu.com 19478082E2F8D3FE
sudo apt update
```

Let me know if that works for you.

**Comment by joelslaby** [comment]
That works! Thank you, you're a legend.
