### ISSUE TITLE
LLVM is required

### ISSUE THREAD

**Issue by jamesoncollins** [GobySoft/goby3#210]
I'm not positive, but it seems to me that LLVM is only required for clang.  Yet, the find_package command for llvm is marked as required.

https://github.com/GobySoft/goby3/blob/74ebe229c41070710a6aeb7a0f572075567ed816/cmake_modules/FindLLVMForGoby.cmake#L26

**Comment by tsaubergine** [comment]
I think you're right that the "REQUIRED" can be removed.

LLVM is used by `goby_clang_tool`, which shouldn't build if LLVM isn't found.
