### ISSUE TITLE
segfault with newer protobuf 3.17.3 and c++14

### ISSUE THREAD

**Issue by jamesoncollins** [GobySoft/goby3#215]
I'm working on cross compiling goby3 with a newer version of protobuf.

I've found that I get a segfault during protobuf initialization if I leave the c++ standard set to 14.  Changing to 17 makes the segfault go away.

The issue appears to be the same as the one documented [here](https://github.com/protocolbuffers/protobuf/issues/8957), so it might be an upstream issue.

**Comment by tsaubergine** [comment]
Is this still a problem? If so, can you suggest a patch to CMake to set C++17 when this is the case?

**Comment by tsaubergine** [comment]
Closing from lack of info, please reopen if this continues to cause problems.
