### ISSUE TITLE
Compile issues with Goby3.0.15

### ISSUE THREAD

**Issue by jcollins-baesystems** [GobySoft/goby3#289]
Our older software ran using goby 3.0.0~alpha with dccl3 on a debian Jessie / Stretch OS. I am attempting to upgrade the OS to Debian Bullseye and updating program dependencies as needed. While attempting to compile Goby3, I have started to run into compilation issues. I have attempted to use multiple versions of dccl to get around them, but they still occur. maybe you could provide assistance?

When compiling with dccl-4.0.3 I observe the following error:
```
/Linux/pub/MOOS/goby3-3.0.15/build/include/goby/middleware/marshalling/dccl.h:153:78: error: no matching function for call to ‘dccl::DynamicProtobufManager::new_protobuf_message<std::shared_ptr<google::protobuf::Message> >(const string&, bool&)’

  153 |             std::shared_ptr<google::protobuf::Message>>(type, user_pool_first);
```

when compiling with dccl-3.0:
```
/Linux/pub/MOOS/goby3-3.0.15/build/include/goby/middleware/marshalling/dccl.h: In static member function ‘static std::shared_ptr<google::protobuf::Message> goby::middleware::SerializerParserHelper<google::protobuf::Message, 2>::parse(CharIterator, CharIterator, CharIterator&, const string&, bool)’:

/Linux/pub/MOOS/goby3-3.0.15/build/include/goby/middleware/marshalling/dccl.h:153:78: error: no matching function for call to ‘dccl::DynamicProtobufManager::new_protobuf_message<std::shared_ptr<google::protobuf::Message> >(const string&, bool&)’

  153 |             std::shared_ptr<google::protobuf::Message>>(type, user_pool_first);

      |                                                                              ^

```

Thoughts?

**Comment by tsaubergine** [comment]
Hi -

Newer versions of Goby3 don't support DCCL3 as this isn't a priority for me. If it's important I'm happy to accept patches for this (should be pretty straightward to use the old call to new_protobuf_message within a #if / #else / #endif cpp block checking for major DCCL version).

I just tested Goby 3.0.15 with DCCL 4.0.3 and it built fine for me. Perhaps you're not using the headers you think you are? 

If it's helpful I distribute .deb packages of the latest releases (currently DCCL 4.0.3 / Goby 3.0.16) for Debian/Ubuntu distros: https://packages.gobysoft.org/debian/release/bullseye/. See https://goby.software/3.0/index.html#autotoc_md111

**Comment by jcollins-baesystems** [comment]
Thank you for the quick response. I will double check to make sure I am using the correct headers. I'm almost positive I was. I will try again to use DCCL 4.0.3. I did try to run ./DEPENDENCIES but the issue is I am using a i686 architecture and it does not appear you have included an i686 .deb packages in the release. For reference our development platform is Linux bbb-devel-d11 5.10.0-23-686 #1 SMP Debian 5.10.179-1 (2023-05-12) i686 GNU/Linux. We perform our development and then typically cross-compile to armhf.

Edit:
I was able to get it to compile with Goby 3.0.15 and DCCL 4.0.3 it seems there was some environment issue. I had dccl 4.0.3 and dccl 3.0.16 in the same folder outside of Goby. even though I set my DCCL_DIR to point to the DCCL4.0.3 build.sh would overwrite it to point to dccl-3.0.16 which would cause issues.

With regards to i686 is that something you might be able to build in the future and include on packages.gobysoft.org? for users of this architecture?

**Comment by tsaubergine** [comment]
Yes, I could include i386 package builds, which is what I assume your Debian package architecture is (dpkg --print-architecture).

Pretty much no one I know uses that architecture any more which is why I haven't bothered to build it (just amd64, armhf, arm64).

**Comment by tsaubergine** [comment]
I don't plan to support packages for i386 as Debian kernel, d-i, etc. are dropping their support: https://www.phoronix.com/news/Debian-Plans-Cease-i386

I will continue to package for the amd64, armhf, and arm64 architectures for Ubuntu LTS and Debian oldstable, and stable
