### ISSUE TITLE
Goby3 message info tool

### ISSUE THREAD

**Issue by jmount-boss** [GobySoft/goby3#302]
Would there be a benefit in creating something analogous to `rosmsg info` to be able to quickly see a message in greater detail? Currently, the only way that I am aware of looking at message details is to open the source file.

**Comment by tsaubergine** [comment]
Probably falls under: https://github.com/GobySoft/goby3/wiki/proposal-1-command-line-tool

**Comment by jmount-boss** [comment]
I would agree it would fall under a unified goby tool
