### ISSUE TITLE
goby_launch should have a way to tag commands that need to be cleaned up

### ISSUE THREAD

**Issue by rgov** [GobySoft/goby3#42]
From a discussion elsewhere:

Is it just going to like `killall socat`? Maybe it would be better for the launch script to be able to tag a command, like one of:

```
[kill=SIGTERM] socat --whatever
[not-goby] socat --whatever
```

Then the launch tool can know that it needs to grab the PID of the launched subprocess and kill it later.

**Comment by tsaubergine** [comment]
Not that it matters now (since this changes in #50), but it would kill only the PIDs matching that name in the current launchfile (not other instances of socat running, for example).
