### ISSUE TITLE
There should be a way to send a message from the command line

### ISSUE THREAD

**Issue by rgov** [GobySoft/goby3#54]
See #53 for one use case.

It should be possible to publish a message from the command line. This could be the API used by shell scripts, web GUIs, etc. for interacting with a Goby3-based system.

I envision a tool that reads from standard input and is invoked something like:

    goby_publish --socket goby.sock --domain interprocess --group asdf --scheme foobar

It would be up to the sender of the message to pack it in the appropriate format corresponding to the scheme.

**Comment by rgov** [comment]
For debugging, it would be interesting to be able to inject an interthread message also. Seems better done as a gdb script or something, so that the application doesn't need to hold open a connection to gobyd if it doesn't want it.

**Comment by tsaubergine** [comment]
Agreed. Began a proposal here: https://github.com/GobySoft/goby3/wiki/Proposal-1-Command-line-tool

**Comment by tsaubergine** [comment]
Implemented in https://github.com/GobySoft/goby3/pull/312

See for details:
`goby zeromq help subscribe`
`goby zeromq help publish`
