### ISSUE TITLE
Use of date in log filename should not be required

### ISSUE THREAD

**Issue by rgov** [GobySoft/goby3#57]
> file_name string must contain \"%1%\" which is expanded to the current application start time (e.g. 20190201T184925)

I don't think this should be enforced. I envision needing to write tests that spawn a set of Goby applications and then grep the debug log for specific warnings, etc.

Normally I would generate a temporary filename and specify that as the log file path. But since you enforce that the filename is dynamic, I would have to then apply a glob pattern to find the generated log file---easy in a shell script, less easy in Python, and tedious in C++.

It just seems like this is something Goby doesn't need to have an opinion of. If I give it the same name as an existing file, and you don't want to append, then that's fine, just die with an error, perhaps giving the hint to include `%1%` to prevent collisions. People will figure it out.

**Comment by tsaubergine** [comment]
The latest log file is symlinked automatically to "foo_latest.txt" for "foo_%1%.txt". 
For example:
```
gobyd_20190201T184743.txt
gobyd_latest.txt -> /media/data/logs/debug/gobyd_20190201T184743.txt
```

The point of this requirement is to ensure that people are not accidentally overwriting their logs by a poor choice of `file_name`. This is more important to me than the slight inconvenience of following this symlink.
