### ISSUE TITLE
Unify Protobuf CMake modules across projects

### ISSUE THREAD

**Issue by rgov** [GobySoft/goby3#58]
cgsn-mooring's FindProtobufLocal.cmake varies slightly from Goby3's FindProtobufGoby.cmake, though they both define the same functions.

One consequence of this is that if you add Goby3 sources to a build with `add_subdirectory()`, the re-defined functions will replace the parent project's definitions.

CMake has an official built-in [FindProtobuf module](https://github.com/Kitware/CMake/blob/master/Modules/FindProtobuf.cmake) as well that has been significantly overhauled. It supports the `PROTOC_OUT_DIR` option now which might do some of what you want.

**Comment by rgov** [comment]
I confirmed that the `generate_protobuf_cpp` function is the only one that is redefined when including Goby3 as a subproject. (See [this CMake issue](https://gitlab.kitware.com/cmake/cmake/issues/14961) on redefinitions of macros and functions.)

Renaming the function to `goby_generate_protobuf_cpp` worked around the issue for me.

**Comment by tsaubergine** [comment]
I don't think I can do `--dccl_out` and `--cpp_out` in the same command with the official CMake FindProtobuf module.
I will leave this open for renaming the function to `goby_generate_protobuf_cpp`, though.

**Comment by mathstuf** [comment]
Protobuf upstream also has their own `protobuf-config` shipping with CMake functions in it. It has a unified API rather than a per-language call though.

https://github.com/protocolbuffers/protobuf/blob/1509e8e3b3d10a2a903f60d6281e30e51b8ecba5/cmake/protobuf-config.cmake.in#L10

**Comment by mathstuf** [comment]
I think it started showing up in 3.4 if that matters.

**Comment by tsaubergine** [comment]
Cool, thanks. May be helpful for the future. For now I need to support protobuf as old as 2.6.1 and CMake as old as 3.5.1
