### ISSUE TITLE
LeakSanitizer reports leaks in several tests

### ISSUE THREAD

**Issue by rgov** [GobySoft/goby3#61]
I imagine that these have a common origin. Is it just the omission of a call to `dccl::DynamicProtobufManager::protobuf_shutdown()`?

e.g., 
[goby_test_queue6.log](https://github.com/GobySoft/goby3/files/2830066/goby_test_queue6.log)

```
build/test-out//goby_test_queue4.log:==4835==ERROR: LeakSanitizer: detected memory leaks
build/test-out//goby_test_queue5.log:==4839==ERROR: LeakSanitizer: detected memory leaks
build/test-out//goby_test_queue6.log:==4843==ERROR: LeakSanitizer: detected memory leaks
build/test-out//goby_test_queue2.log:==4827==ERROR: LeakSanitizer: detected memory leaks
build/test-out//goby_test_queue3.log:==4831==ERROR: LeakSanitizer: detected memory leaks
build/test-out//goby_test_queue1.log:==4823==ERROR: LeakSanitizer: detected memory leaks
build/test-out//goby_test_middleware5.log:==4998==ERROR: LeakSanitizer: detected memory leaks
```

**Comment by tsaubergine** [comment]
I suspect these are all fixed by: https://github.com/GobySoft/dccl/tree/3.0-dynamic-protobuf-manager

**Comment by tsaubergine** [comment]
I intend to merge that branch in soon.

**Comment by rgov** [comment]
I can confirm that all leaks are related to the protobuf manager not being shutdown. I won't open a pull request but here are the changes needed:

[0001-Shutdown-the-DynamicProtobufManager-to-appease-LeakS.txt](https://github.com/GobySoft/goby3/files/2830097/0001-Shutdown-the-DynamicProtobufManager-to-appease-LeakS.txt)

**Comment by tsaubergine** [comment]
Cool - go ahead and open a PR for this.
