### ISSUE TITLE
SimpleThreads should set the thread name

### ISSUE THREAD

**Issue by rgov** [GobySoft/goby3#64]
A basic MultiThreadApplication seems to have 6+ threads running even in a simple application. When I look at `info threads` in GDB, I can't tell them apart.

I don't care so much about Goby's internal threads, but any threads I start up using `launch_thread()`, I'd like to be able see the class name associated with it.

**Comment by tsaubergine** [comment]
Is there a way to do this with std::thread?

**Comment by rgov** [comment]
On BSD, you can call `pthread_setname_np()` which applies to the current thread, without needing a reference to it. On Linux, you need a reference to the thread, i.e., `pthread_self()`.

A challenge is also that you are limited to 16 bytes, including the NULL byte.

**Comment by tsaubergine** [comment]
Yes, but but for std::thread (which I know is implemented using pthread on Linux, but would rather not count on that?

**Comment by rgov** [comment]
[This is what StackOverflow thinks.](https://stackoverflow.com/a/10121671/145504)

You could make a global function that helps mapping things, I guess, like `call (char *)get_thread("PluginThread")`. Or just use preprocessor directives to cut out setting the thread name on other platforms... pthreads will be around for a while.
