### ISSUE TITLE
Lots of noise from -Wdocumentation

### ISSUE THREAD

**Issue by rgov** [GobySoft/goby3#66]
I don't know where this flag gets set but it makes Clang generate a lot of noise from `acomms/amac/mac_manager.h` and `acomms/queue/queue_manager.h` which are included all over the place and make it difficult for me to see what warnings/errors are in my own code.

Most of the messages seem to be that it doesn't like when you are trying to use `\param` to document an argument of a function pointer type, like here:

```
    /// \brief Forwards the data request to the application layer. This advanced feature is used when queue.encode_on_demand == true and allows for the application to provide data immediately before it is actually sent (for highly time sensitive data)
    ///
    /// \param request_msg the details of the requested data. (protobuf::ModemDataRequest is defined in acomms_modem_message.proto)
    /// \param data_msg pointer to store the supplied data. The message is of the type for this queue.
    boost::signals2::signal<void(const protobuf::ModemTransmission& request_msg,
                                 google::protobuf::Message* data_msg)>
        signal_data_on_demand;
```

Doxygen *does* [show this in the output](http://gobysoft.org/doc/3.0/classgoby_1_1acomms_1_1QueueManager.html#a37f3e30e51d7fd1c4aa872ce7987fbac) even if it is not entirely valid.

**Comment by tsaubergine** [comment]
Yeah, I wrote this long before -Wdocumentation existed (it's a Clang flag, set in cgsn-mooring, not in Goby3). 

Not sure why you're seeing this unless you're building Goby with -Wdocumentation?

**Comment by rgov** [comment]
I am not currently doing an in-tree build of Goby3 but maybe my build directory has some remnants. I tried adding -Wno-documentation to the flags override but it didn't help.

```
In file included from ../src/bin/sensor/presf_sbe/presf_sbe.cpp:18:
In file included from include/cgsn-mooring/serial/ascii_line_based_serial.h:25:
In file included from include/cgsn-mooring/serial/serial.h:31:
In file included from include/goby/middleware/multi-thread-application.h:33:
In file included from include/goby/middleware/transport-intervehicle.h:35:
In file included from include/goby/acomms/bind.h:34:
In file included from include/goby/acomms/queue.h:28:
```

My guess is that one of the ones at the top of this list does not use angle brackets. I'll fix it if that's the case. **Edit:** Apparently that doesn't help.
