### ISSUE TITLE
cmake fails if MOOS not found

### ISSUE THREAD

**Issue by russkel** [GobySoft/goby3#76]
While trying to build #75 I came across this issue which is a result of a recent commit.

I am not familiar with cmake enough to offer a patch.

```
>> Could not find MOOS v10, trying to find MOOS pre-v10.
>> setting build_moos to OFF ... if you need this functionality: 1) install MOOS and libproj-dev; 2) run cmake -Dbuild_moos=ON
-- Configuring done
CMake Error: INSTALL(EXPORT) given unknown export "goby_moos-config"
-- Generating done
```

**Comment by tsaubergine** [comment]
I will fix the error message, but I don't think CMake is failing here.

Toby

**Comment by russkel** [comment]
Maybe not, however it still causes my alpine build script to fail (non-zero return code presumably), and likely for other build systems.

**Comment by russkel** [comment]
This is fixed. Thanks.
