### ISSUE TITLE
CMake cannot find MOOS if installed into system

### ISSUE THREAD

**Issue by russkel** [GobySoft/goby3#83]
I have created Alpine packages for MOOS-IVP. When these are installed into the system (/usr/lib and /usr/include) there is, of course, no source tree any more. Does Goby really need the source tree in order to compile, or is access to the includes and libs enough?

```
>> Could not find MOOS v10, trying to find MOOS pre-v10.
>> setting build_moos to OFF ... if you need this functionality: 1) install MOOS and libproj-dev; 2) run cmake -Dbuild_moos=ON
```

**Comment by russkel** [comment]
This is probably an issue with the EXPORTED MOOS cmake file. Disregard.

**Comment by tsaubergine** [comment]
Yes, it's looking for the exported CMake file. I had to patch it to make a working Debian package (at least in 10.0.2, which is the last version I've used):
https://github.com/GobySoft/core-moos-debian/blob/master/patches/02-export-config

**Comment by russkel** [comment]
That's quite helpful. Thanks.
